- name: Checkout my dotfiles
  git:
    repo: git@github.com:naofumi-fujii/dotfiles-private.git
    dest: ~/dotfiles

- name: Create symlinks
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .tmux.conf
    - .zshrc
    - .gitconfig
    - .gitignore_global
    - .vimrc
    - .bundle
    - .gemrc
    - .pryrc

- name: Create folder
  file:
    dest: ~/.config/nvim
    state: directory

- name: Create symlink for neovim
  file:
    src:  ~/dotfiles/.vimrc
    dest: ~/.config/nvim/init.vim
    force: yes
    state: link
