# - name: Checkout my dotfiles
#   git:
#     repo: git@github.com:naofumi-fujii/dotfiles-private.git
#     dest: ~/dotfiles

- name: ghq get my dotfiles
  ansible.builtin.command: ghq get git@github.com:naofumi-fujii/dotfiles-private.git


- name: Create symlinks
  file:
    src: ~/src/github.com/naofumi-fujii/dotfiles-private/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .tmux.conf
    - .zshrc
    - .gitconfig
    - .gitignore_global
    - .vimrc
    - .bundle
    - .gemrc
    - .pryrc
    - .zsh_history

- name: Create folder
  file:
    dest: ~/.config/nvim
    state: directory

- name: Create symlink for neovim
  file:
    src:  ~/dotfiles/.vimrc
    dest: ~/.config/nvim/init.vim
    force: yes
    state: link
